compile:
	g++ -o helltrace areaLight.cpp color.cpp conicCam.cpp engine.cpp lexer.cpp log.cpp main.cpp phong.cpp pixelBuff.cpp plane.cpp postProcess.cpp resourceManager.cpp scene.cpp sphere.cpp task.cpp utilities.cpp vector3.cpp executor.cpp

clean:
	rm helltrace
	
